### PR TITLE
Test that a trivial pentagon can be built

### PR DESCRIPTION
**Pull request by saraedum**
this has been failing for me locally but maybe I am doing something
wrong.

### CODE REVIEW

**Comment by saraedum** [comment]
Yes, same problem that I've been seeing also happens in the CI:
```
        sage: E = EquiangularPolygons(1, 1, 1, 1, 1)
        sage: E(1, 1, 1, 1, 1)
```
fails with
```
File "flatsurf/geometry/polygon.py", line 1940, in flatsurf.geometry.polygon.EquiangularPolygons

Failed example:

    E(1, 1, 1, 1, 1)

Exception raised:

    Traceback (most recent call last):

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run

        self.compile_and_execute(example, compiler, test.globs)

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute

        exec(compiled, globs)

      File "<doctest flatsurf.geometry.polygon.EquiangularPolygons[27]>", line 1, in <module>

        E(Integer(1), Integer(1), Integer(1), Integer(1), Integer(1))

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/flatsurf/geometry/polygon.py", line 2199, in __call__

        raise ValueError("the provided lengths do not give rise to a polygon")

    ValueError: the provided lengths do not give rise to a polygon
```

**Comment by videlec** [comment]
This is not a bug. The slope vectors are not normalized to be unit length (otherwise you might need to increase the number field). If you want to provide length (and not coefficient of the slope vectors), use
```
sage: from flatsurf import *
sage: E = EquiangularPolygons(1, 1, 1, 1, 1)
sage: E(1, 1, 1, 1, 1, normalized=True)
Polygon: (0, 0), (1, 0), (1/2*c^2 - 1/2, 1/2*c), (1/2, 1/2*c^3 - c), (-1/2*c^2 + 3/2, 1/2*c)
```

**Comment by videlec** [comment]
Travis reports errors with sage-9.0 and sage-9.1 (beyond the test added in that branch)

**Comment by saraedum** [comment]
These come from changes in pyeantic/pyexactreal. They are fixed in #51 already.

**Pull request merged**
