### PR TITLE
implement from_pyflatsurf conversion

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec This should work. Should we release sage-flatsurf 0.4.0 once this has been merged?

I could add rever packaging to make this easier.

**Comment by saraedum** [comment]
The CI is unhappy with libflatsurf somehow. Let me investigate.

**Comment by videlec** [comment]
I would like to finish `ThurstonVeech` before releasing, #74

**Comment by videlec** [comment]
Having a rever script sounds good. However, releasing is not so complicated with Python packages.

**Comment by saraedum** [comment]
The CI issues are fixed in https://github.com/conda-forge/fmt-feedstock/pull/19.

**Comment by saraedum** [comment]
To fix the remaining issues we need https://github.com/videlec/e-antic/pull/138.

**Pull request merged**
