### PR TITLE
Add a Tour of flatsurf

### LINKED ISSUE #253: Add "A Tour of flatsurf"

### PR DESCRIPTION
**Pull request by saraedum**
fixes #253 

##### TODO
* [x] Added an entry in `doc/news/`. 
* [x] Added a test for this change.
* [x] Added new .py files to the documentation in `doc/geometry` or `doc/graphical`.
* [x] Split cells that produce multiple outputs. Just make sure that each logical section is self-contained.
* [x] Increase the picture density when scrolling through the tour.
* [x] Link to the tour prominently on the sage-flatsurf GitHub page.
* [x] Link to the tour prominently on flatsurf.github.io.

##### Dependencies
* [x] https://github.com/flatsurf/veerer/issues/23

### CODE REVIEW

**Comment by saraedum** [comment]
> I expanded quite a bit the "veerer" part that Martin Möller and Johannes Schwab want to use. Can I commit now?

Yes, please update the `tour.md` file.

**Comment by videlec** [comment]
The output of the cell
```
# you might need to install veerer
# (it is not by default in the flatsurf stack... but soon)
# the command could equally be run in a console
%pip install git+https://github.com/flatsurf/veerer
```
is a bit ugly :-)

**Comment by saraedum** [comment]
Yeah, let's create a veerer release.

**Comment by saraedum** [comment]
@videlec @slel anything else that should be added to the tour? https://deploy-preview-254--cheerful-kulfi-d8aab6.netlify.app/examples/tour

**Comment by videlec** [comment]
> @videlec @slel anything else that should be added to the tour? https://deploy-preview-254--cheerful-kulfi-d8aab6.netlify.app/examples/tour

Yes. I would like to expand the veerer part (at least mentioning #269).

**Comment by saraedum** [comment]
Should we merge this already and then keep adding things to the tour when we merge them into the actual packages (and release them?)

**Comment by videlec** [comment]
> Should we merge this already and then keep adding things to the tour when we merge them into the actual packages (and release them?)

Sounds good to me.

**Pull request merged**
