### PR TITLE
Add another example and binder configuration

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by videlec** [comment]
Could you make a `rst` as in #76 ? Maintaining properly these notebooks with git is a nightmare. Or do you think it is better to have notebooks ?

**Comment by saraedum** [comment]
Can binder display `.rst`?

**Comment by videlec** [comment]
Not that I know but it is easy to convert rst -> ipynb (and it might even be possible to load rst files from the jupyter(lab) notebooks).

**Comment by saraedum** [comment]
Should we try to use https://github.com/mwouts/jupytext?

**Comment by videlec** [comment]
I want these worksheets to be part of the sage-flatsurf documentation. Each notebook could be thought of as an answer in a FAQ. Having them in rst format makes it convenient (eg for indexing and testing).

I don't know how to make that goal fits with notebooks that you can use in binder.

> Should we try to use https://github.com/mwouts/jupytext?

I don't know. It is an additional plugin for jupyter. Not so convenient for users.  And also, not so much `rst` compatible.

**Comment by saraedum** [comment]
We're not the first ones having this problem ;) https://github.com/nthiery/rst-to-ipynb

**Comment by saraedum** [comment]
So, https://myst-nb.readthedocs.io/en/latest/ seems like a good solution actually. Let me try…

**Comment by videlec** [comment]
David also would like to weight the counting with cylinder area (instead of 1 per cylinder). And possibly more fancy weighting.

**Comment by saraedum** [comment]
Unfortunately, we cannot doctest the notebooks easily yet, see https://github.com/executablebooks/MyST-NB/issues/290. However, we also have not been doing that so far.

**Comment by videlec** [comment]
If instead of the notebook we stored a `rst` file then it can be doctested. This is what is done at https://github.com/flatsurf/sage-flatsurf/pull/76.

**Comment by videlec** [comment]
Text outputs are included in the rst (as "sage doctests"). The graphics are indeed not rendered. But it suffices to run the notebook to get them. I don't see disadvantages of using rst files. The ipynb files (with rendered graphcs) could be generated as part as the documentation build.

**Comment by saraedum** [comment]
But then the documentation has no graphics. With the approach here you have all the pictures of the surfaces in the documentation.

**Comment by saraedum** [comment]
Ok. Then let's discuss the details of this tomorrow :)

**Pull request merged**
