### PR TITLE
Make sage-flatsurf work with pyeantic & pyexactreal

### LINKED ISSUE #11: Support e-antic
How would we best support coordinates given with e-antic (pyeantic) coordinates?

### PR DESCRIPTION
**Pull request by saraedum**
fixes #11, #12.

### CODE REVIEW

**Comment by saraedum** [comment]
This is still very much work in progress :)

**Comment by videlec** [comment]
I think that the minimal number field created in the constructor of `EquiangularPolygon` should always be computed and kept as the base ring. The code is smart at finding a reasonable generator where `AA` is not. We had trouble with coefficient blowups using `AA` in the past.

You might want to try to modify only `EquiangularPolygons.__call__` instead of allowing more general base ring. I would even disallow `AA` as a base ring in the constructor. In other words make `EquiangularPolygons.__init__(self, angles)`. But it should still be possible to construct the polygon with elements in `AA` via `EquiangularPolygon.__call__`. Similarly, this construction should be possible with any ring that provides a canonical embedding from `EquiangularPolygons.base_ring()`.

**Comment by saraedum** [comment]
The deprecation warnings have been fixed in https://github.com/networkx/networkx/commit/224bd0ce1cc1c5c55a038da72b399d8540055bd9 which is in networkx 2.4 which is not in SageMath yet. I have no clue why these warnings show up now.

**Comment by saraedum** [comment]
I guess we are now testing with the latest flipper which added its dependency on networkx in https://github.com/MarkCBell/flipper/commit/719b4e38e22df056786650e6f547f199fc69c41b.

**Comment by saraedum** [comment]
In principle this works now. However, this needs some changes to exact-real that I have not merged yet.

Should I add pyexactreal as a dependency for the tests?

**Comment by videlec** [comment]
> Should I add pyexactreal as a dependency for the tests?

Yes, please do.

**Pull request merged**
