### PR TITLE
Documentation Fixes

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Added an entry in `doc/news/`. 
* [x] Added a test for this change. **No**, don't know what to test.
* [x] Added new .py files to the documentation in `doc/geometry` or `doc/graphical`. **Nothing new.**

### CODE REVIEW

**Comment by videlec** [comment]
Since it was compiled on the CI, is there a way to have a look at the documentation without compiling it on my machine?

**Comment by videlec** [comment]
I have some weird error messages when doing `make html`. The first two are due to the fact that I do not have `pyflatsurf` installed. I am not sure that qualifies as a bug (do we assume that `pyflatsurf` is installed when building the documentation?). The last three `Could not lex literal_block as "ipythontb". Highlighting skipped.` are more mysterious to me.
```
Reading sources... [100%] install                                              
.../sage-flatsurf/doc/examples/apisa_wright.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
.../sage-flatsurf/doc/examples/apisa_wright.md: WARNING: Notebook exception traceback saved in: .../sage-flatsurf/doc/_build/html/reports/examples/apisa_wright.err.log [mystnb.exec]
.../sage-flatsurf/doc/examples/boshernitzan_conjecture.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
.../sage-flatsurf/doc/examples/boshernitzan_conjecture.md: WARNING: Notebook exception traceback saved in: .../sage-flatsurf/doc/_build/html/reports/examples/boshernitzan_conjecture.err.log [mystnb.exec]
.../sage-flatsurf/doc/examples/siegel_veech.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
.../sage-flatsurf/doc/examples/siegel_veech.md: WARNING: Notebook exception traceback saved in: .../flatsurf/sage-flatsurf/doc/_build/html/reports/examples/siegel_veech.err.log [mystnb.exec]
.../sage-flatsurf/flatsurf/geometry/surface_objects.py:docstring of flatsurf.geometry.surface_objects.Cylinder:6: CRITICAL: Unexpected section title.

To Do
-----
.../sage-flatsurf/flatsurf/geometry/surface_objects.py:docstring of flatsurf.geometry.surface_objects.Cylinder.plot:9: CRITICAL: Unexpected section title.

Parameters
----------
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] install                                               
.../sage-flatsurf/doc/examples/apisa_wright.md:109: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
.../sage-flatsurf/doc/examples/boshernitzan_conjecture.md:72: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
.../sage-flatsurf/doc/examples/siegel_veech.md:39: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
```

**Comment by saraedum** [comment]
> Since it was compiled on the CI, is there a way to have a look at the documentation without compiling it on my machine?

I am adding a CI job that makes the documentation available. It's already available now as a download in the `build-manual` job. Let me try if I can also make a preview available like SageMath does now.

**Comment by saraedum** [comment]
> I have some weird error messages when doing make html. The first two are due to the fact that I do not have pyflatsurf installed. I am not sure that qualifies as a bug (do we assume that pyflatsurf is installed when building the documentation?).

Yes, we expect all the optionals to be installed so we can compile all the notebooks.

> The last three Could not lex literal_block as "ipythontb". Highlighting skipped. are more mysterious to me.

The highlighting for exception messages in notebooks is not working correctly it seems. (This is caused by the previous errors when rendering the notebooks.)

**Comment by saraedum** [comment]
Please have a look now @videlec .

**Comment by videlec** [comment]
Looks good to me.

**Review by videlec — APPROVED** [review]

**Pull request merged**
