### PR TITLE
veering and L^oo-Delaunay

### PR DESCRIPTION
**Pull request by videlec**
Checklist
* [x] Added an entry in `doc/news/`. 
* [x] Added a test for this change.

- Fix L^oo decomposition of dilation surface
- Implement `.is_veering_triangulated()` and `.veering_triangulation()`

### CODE REVIEW

**Comment by videlec** [comment]
@wphooper I think I fixed the L^oo-Delaunay decomposition. I took the opportunity to include new functions for dilation surfaces
- `is_veering_triangulated`
- `veering_triangulation` (which is similar to L^oo-Delaunay but might require less flips)

**Comment by videlec** [comment]
@saraedum [videlec:fix-l-infinity-delaunay](https://github.com/videlec/sage-flatsurf/tree/fix-l-infinity-delaunay) which is supposedly the branch on which this PR is based on differ from the visible commit here. Namely [a9ab1dd](https://github.com/flatsurf/sage-flatsurf/pull/269/commits/a9ab1dd6e418e852c97db83c2f269602d6ab9a2f) should be replaced with [51b3d3d](https://github.com/videlec/sage-flatsurf/commit/51b3d3d934978752dc3688905569d4885818a358). Do you know a way to fix it simpler than opening a new PR?

**Comment by wphooper** [comment]
The updated code is working well for me, with no errors so far. Thanks Vincent for the code!

I do however have a complaint: In a `VeeringTriangulation`, the triangles seem to have a well defined order (e.g. in `triangulation()` and `faces()`). There is a natural bijection between the triangles and the rectangles making up the surface produced by `zippered_rectangles()`, but the labels of the rectangles does not match the order of triangles. It would be much easier to use if the rectangles were labeled to match the position of the triangles in say `faces()`. (As it is, the identification between the surface represented by the `VeeringTriangulation` and the `zippered_rectangle()` surface is hard to find.

(In my use case, I understand the action of a pseudo-Anosov on say the horizontal prongs in a triangulated surface, and want to use this to understand of the action on rectangles. Because the labels of rectangles seem random, this is more difficult than it should be.)

I'll be playing with this more. I expect to eventually contribute some code for pseudo-Anosovs and Markov partitions.

**Comment by videlec** [comment]
> I do however have a complaint: In a `VeeringTriangulation`, the triangles seem to have a well defined order (e.g. in `triangulation()` and `faces()`). There is a natural bijection between the triangles and the rectangles making up the surface produced by `zippered_rectangles()`, but the labels of the rectangles does not match the order of triangles. It would be much easier to use if the rectangles were labeled to match the position of the triangles in say `faces()`. (As it is, the identification between the surface represented by the `VeeringTriangulation` and the `zippered_rectangle()` surface is hard to find.

Hopefully fixed in https://github.com/flatsurf/veerer/pull/40

**Pull request merged**
