### PR TITLE
fix GitHub pages output

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec: There is a problem in one of the examples: https://github.com/flatsurf/sage-flatsurf/pull/84/checks?check_run_id=2346189624

Can this be fixed easily?

**Comment by saraedum** [comment]
Another problem:
```
  ---------------------------------------------------------------------------
  AttributeError                            Traceback (most recent call last)
  <ipython-input-34-517a65e7fef3> in <module>
  ----> 1 v=B(s.base_label(),(Integer(1)/Integer(4),Integer(1)/Integer(4)),(-Integer(1),Integer(1)))
        2 traj=v.straight_line_trajectory()
        3 traj.flow(Integer(100))
        4 if traj.is_closed():
        5     print("The trajectory closed up.")
  
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/flatsurf/geometry/tangent_bundle.py in __call__(self, polygon_label, point, vector)
      445         in the base field."""
      446         V = self.vector_space()
  --> 447         return SimilaritySurfaceTangentVector(self, polygon_label, self._V(point), self._V(vector))
      448 
      449     def __repr__(self):
  
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/flatsurf/geometry/tangent_bundle.py in __init__(self, tangent_bundle, polygon_label, point, vector)
       58         self._bundle = tangent_bundle
       59         p = self.surface().polygon(polygon_label)
  ---> 60         pos = p.get_point_position(point)
       61         if vector == self._bundle.vector_space().zero():
       62             raise ValueError("Provided vector is zero. (Temporarily not supported.)")
  
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/sage/structure/element.pyx in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4701)()
      491             AttributeError: 'LeftZeroSemigroup_with_category.element_class' object has no attribute 'blah_blah'
      492         """
  --> 493         return self.getattr_from_category(name)
      494 
      495     cdef getattr_from_category(self, name):
  
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/sage/structure/element.pyx in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4813)()
      504         else:
      505             cls = P._abstract_element_class
  --> 506         return getattr_from_other_class(self, cls, name)
      507 
      508     def __dir__(self):
  
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/sage/cpython/getattr.pyx in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2552)()
      365         dummy_error_message.cls = type(self)
      366         dummy_error_message.name = name
  --> 367         raise AttributeError(dummy_error_message)
      368     cdef PyObject* attr = instance_getattr(cls, name)
      369     if attr is NULL:
  
  AttributeError: 'Polygons_with_category.element_class' object has no attribute 'get_point_position'
  AttributeError: 'Polygons_with_category.element_class' object has no attribute 'get_point_position'
```

**Comment by saraedum** [comment]
And this one
```
   Traceback (most recent call last):
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
      executenb(
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
      return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
      return just_run(coro(*args, **kwargs))
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
      return loop.run_until_complete(coro)
    File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
      return future.result()
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
      await self.async_execute_cell(
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 841, in async_execute_cell
      exec_reply = await self.task_poll_for_reply
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 646, in _async_poll_for_reply
      await self._async_handle_timeout(timeout, cell)
    File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 696, in _async_handle_timeout
      raise CellTimeoutError.error_from_timeout_and_cell(
  nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
  The message was: Cell execution timed out.
  Here is a preview of the cell contents:
  -------------------
  ['# Build intersection graph', 'd={}', 'for i in range(len(sc_list2)):', '    for j in range(i+1,len(sc_list2)):', '        if not sc_list2[i].intersects(sc_list2[j]):']
  ...
  ['                d[i].append(j)', '            if j not in d:', '                d[j]=[i]', '            else:', '                d[j].append(i)']
  -------------------
```

**Comment by videlec** [comment]
> @videlec: There is a problem in one of the examples:
> 
> <SNIP>
>    ------------------
>   spt = s.surface_point(7,pt)
>   spt
>   ------------------

The problem is that the layout was not deterministic and changed. From the very beginning, the document does not discuss the `GraphicalSurface` that is actually constructed by `gs = s.graphical_surface()` in the fourth cell. @wphooper, I am not sure how you want to fix the `graphics_configuration.ipynb`.

**Comment by videlec** [comment]
The layout that used to be here
layout-old
The layout that we obtain now
layout-now

**Comment by wphooper** [comment]
I guess the issue is that I call things from `sage.geometry.polyhedron` and something there must have changed between sage versions. I guess the simplest thing is to just use a different example surface.

I'm sorry I haven't been following along. How are you converting back and forth between markdown and ipynb? This is great you can now test these examples!

**Comment by videlec** [comment]
> I guess the issue is that I call things from `sage.geometry.polyhedron` and something there must have changed between sage versions. I guess the simplest thing is to just use a different example surface.

I propose to drop `graphics_configuration` for now from the list of our notebooks and open a distinct pull request to bring it back. Would that be ok?

> I'm sorry I haven't been following along. How are you converting back and forth between markdown and ipynb? This is great you can now test these examples!

Yes indeed! And furthermore, updating them and tracking them in git will be easier.

**Comment by saraedum** [comment]
> How are you converting back and forth between markdown and ipynb?

With [myst-nb](https://myst-nb.readthedocs.io/en/latest/) and [jupytext](https://github.com/mwouts/jupytext).

**Comment by saraedum** [comment]
@videlec we still have `AttributeError: 'Polygons_with_category.element_class' object has no attribute 'get_point_position'` that needs to be adrdessed.

**Comment by videlec** [comment]
Samuel also mentioned the issue on zulip. The `get_point_position` exists for `ConvexPolygon` but not `Polygon`.

**Comment by videlec** [comment]
See #93

**Comment by saraedum** [comment]
> Samuel also mentioned the issue on zulip. The `get_point_position` exists for `ConvexPolygon` but not `Polygon`.

Sorry, I don't really understand how to fix this one. Should we implement `get_point_position`? Or can we somehow use `ConvexPolygon` in this test case? (The problem is in `doc/examples/warwick-2017.md`.)

**Comment by videlec** [comment]
Each individual polygon is built through one of the parent `Polygons` or `ConvexPolygons`. The latter used to be called `Polygons` and the non-convex version was introduced to handle billiards in the plane. In most situations we should
- change `Polygons` to `ConvexPolygons` (that should solve the bug)
- add a `get_point_position` to `Polygon` (which are not necessarily convex)

**Pull request merged**
